trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: MavenAuthenticate@0
  inputs:
    mavenServiceConnection: 'YourMavenServiceConnection'
    mavenPomFile: 'pom.xml'
    options: '-Xmx3072m'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package test'
    options: '-Xmx3072m'
